### ISSUE TITLE
kaga make user?

### ISSUE THREAD

**Issue by buncis** [SMTI07/blog-smti#7]
@vianhanif @jefriyh ini jadinya kaga make user apa begimana?

**Comment by vianhanif** [comment]
nanti klo user dah jadi, tinggal d atur d controller aja kok bsa... biar model2'a g perlu nunggu

**Comment by buncis** [comment]
lah kan belongs_to nya harus ada usernya yaudah tar gua buat user_id:integer field aja

**Comment by edwinfachri** [comment]
<3

**Comment by anggaku** [comment]
@vianhanif itu gua udah bikin user dah, gua bikinnya masih di console, yang datu usernya dapet role admin_role dan yang satu dapet role nya user_role,
