### ISSUE TITLE
database postgresqnya make encodingnya SQL_ASCII, ada issue kompatibilitas

### ISSUE THREAD

**Issue by buncis** [SMTI07/blog-smti#9]
mungkin karena di initnya dari alvian dia make mac
kita rubah aja ke unicode lebih universal

**Comment by vianhanif** [comment]
itu tdi k rubah gtu karna di suryadi hrus gtu, d gw awal'a jga unicode

**Comment by buncis** [comment]
berarti suryadi penyebab kesalahannya al 
iya soalnya selama ini lo kaga make SQL_ASCII kan

@xgunawan elu ya sur pelakunya?

**Comment by vianhanif** [comment]
pake [Cloud9](https://c9.io/) dia ndrey~

**Comment by xgunawan** [comment]
gue pake c9 jadi gitu dre. biasanya bisa2 aja D:
